[package]
name = "platformer-bevy-ldtk"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_ecs_ldtk = "0.12.0"
bevy_rapier2d = "0.30.0"
# We only need this dependency for removing TileColor from ldtk...
bevy_ecs_tilemap = "0.16.0"

# [profile.dev]
# debug = "line-tables-only"
